version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.8.4
    container_name: beatmatch_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - TZ=America/Sao_Paulo
    volumes:
      - .:/home/node/beatmatch_hub
      - /home/Usuario/.n8n:/home/node/.n8n


